### ISSUE TITLE
Create "file list block" which works like File Block but supports multiple files

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-elemental-blocks#2]

**Comment by robbieaverill** [comment]
@clarkepaul, are we going to do it this way or create a different block?

**Comment by clarkepaul** [comment]
"Image block" is singular upload and only accepts images, this is the one that banner feeds off. 

The other blocks which are not part of the first sprint:
"File list block" needs multi upload
"Media block" needs singular upload (used for displaying video, audio etc.) but not part of core yet.

**Comment by robbieaverill** [comment]
Ok, we should go through at some stage and log these all as new enhancement issues.

**Comment by robbieaverill** [comment]
Renamed

**Comment by michalkleiner** [comment]
Wouldn't it be better to just allow the file block to hold multiple files (and optionally rename it)? The number of files can be limited within the upload field config if needed.

**Comment by robbieaverill** [comment]
>Wouldn't it be better to just allow the file block to hold multiple files (and optionally rename it)? The number of files can be limited within the upload field config if needed.

I think that would be easier from a development perspective, but it might not be from a UX perspective. I'll leave this to @clarkepaul and @sachajudd to decide, but I think this is a future scope for the content blocks work that SS Ltd. has been doing.

**Comment by clarkepaul** [comment]
A "File list block" is a list of links to files while a "Image block" displays as a visual element rather than a link. I think its best to keep them as separate blocks. It might be that there could be a multi file block where you could decide on how its displayed (eg. list of links, as a gallery) but that hasn't been discussed as far as I know—I think it would make more sense to have these as two separate blocks.

**Comment by robbieaverill** [comment]
Issue moved to [silverstripe/silverstripe-elemental-fileblock #1](https://github.com/silverstripe/silverstripe-elemental-fileblock/issues/1) via [**ZenHub**](https://www.zenhub.com/)
