### ISSUE TITLE
small css issue with large text in banner

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-elemental-blocks#31]
If a large block of text is added to the banner, it will overflow the outer box. Lots of (ugly) ways to address this in css, keeping the rest of the page layout intact and users should test, but...

What about a property setting to limit the amount of text displayed?

Martine

**Comment by robbieaverill** [comment]
Thanks for reporting @Martimiz. We'd discussed when doing the initial dev work, and decided not too complicated with the example stylesheets. They're really aimed at examples for users, and we'd fully expected users to override the defaults when using them.

If you're keen to make a pull request for this that'd be great, but the core team probably won't be looking to address this issue.

**Comment by Martimiz** [comment]
OK, get it :) I'll think about a way to do this properly :)
