### ISSUE TITLE
The Documentation section in README doesn't link anywhere

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-elemental-blocks#36]
Not sure where it should link to, as there aren't any docs at the moment. Would be good to have some docs written that show default examples of each of the different blocks available in the module.

See: https://github.com/silverstripe/silverstripe-elemental-blocks#documentation

**Comment by robbieaverill** [comment]
Yeah true, we even say "see the user guide documentation" which doesn't exist. https://github.com/silverstripe/silverstripe-elemental-blocks#documentation

**Comment by madmatt** [comment]
Thanks @brynwhyman!

**Comment by brynwhyman** [comment]
See #39 for new card for creating documentation.
