### ISSUE TITLE
Expand block previews

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-elemental-blocks#43]
## User Story

As a CMS user, I want to be able to expand block previews to view the fields of the block, so that I can view the block contents within a page view.

## Acceptance Criteria

- [x] An expand arrow is displayed on the block preview.
- [x] The arrow changes from down to up when the block is expanded and vise versa.
- [x] The block can be collapsed again by clicking the up arrow. The block fields will disappear and be replaced by the mini preview.
- [x] When I click on the expand arrow the mini preview disappears and the block expands to show the editable fields associated to that block.
- [x] The expand/collapse icons are keyboard accessible
- [ ] ~If the block has content that is currently saved, this content is presented when the block is expanded.~ https://github.com/silverstripe/silverstripe-elemental-blocks/issues/42
- [ ] If the block has content that is currently published and no saved draft content, the published content is displayed when expanded.
- [x] For blocks that can't be expanded (like user forms) the 'expand arrow' should point to the right and direct the user to the GridDetailForm when clicked (as defined in #266)

### Notes
- No functionality to record edited fields is required for this issue.
- Use a placeholder for content

**Comment by ScopeyNZ** [comment]
I can't see in the designs any idea of mini-preview vs big-preview. I understand that we'll be showing an inline form on expand but I wonder whether we should go to the effort of having a "big preview" just to implement a form in its place later?

I probably missed something so please let me know.

cc @brynwhyman @clarkepaul

**Comment by brynwhyman** [comment]
Nice spotting @ScopeyNZ, the user story isn't clear enough. The idea here is that the inline form should be displayed:
"so that I can ~preview~ *view* the block contents within a page view."

and updated the AC:
"When I click on the expand arrow the mini preview disappears and the block expands to show the *editable* fields associated to that block.""

Can re-point if required.

**Comment by ScopeyNZ** [comment]
Should it or shouldn't it include saving? Does this mean the "edit icon" AC is still relevant? I think it probably deserves further discussion (and potentially a re-estimation) - maybe chat on Monday morning about this one?

**Comment by brynwhyman** [comment]
This was intended to focus on expanding functionality only. Inline editing and saving at a page level are covered here: https://github.com/silverstripe/silverstripe-elemental-blocks/issues/42

and saving blocks individually are covered here: https://github.com/dnadesign/silverstripe-elemental/issues/290

**Comment by chillu** [comment]
>  The expand/collapse icons are keyboard accessible

Minor detail, but just calling out that you shouldn't get in a habit of adding this to your ACs. Building accessible UIs should be part of your DoD, just like cross browser testing is. Otherwise devs will ignore it unless it's in the ACs ;) If you think it's in danger of being dropped, add it to the notes.
