### ISSUE TITLE
Update readme to help remove confusion

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-elemental-blocks#45]
People looking at Elemental for the first time (e.g. in an evaluation phase) may come across this module, then wonder why composer will not let them install it with newer versions of Elemental.

The Readme currently states that this module is deprecated and that the blocks it contains can be installed individually, however this is sometimes extra overhead - understanding that this does not mean that the blocks themselves are deprecated, which blocks this module contained, that the referenced modules in the readme are exact equivalents of this module (there is no missing functionality with all are installed together), and that there is in fact a recipe that essentially replaces this module entirely in terms of what it offers with a single dependency.

I propose that https://github.com/silverstripe/recipe-content-blocks be referenced in the readme directly, suggesting that this be used instead. Perhaps there is also something that could be done with composer to indicate that the recipe replaces this deprecated module.

**Comment by ScopeyNZ** [comment]
Would you like to submit a PR?

**Comment by NightJar** [comment]
I would. When I've got time ;)

**Comment by NightJar** [comment]
PR: #46
